### ISSUE TITLE
Panic on `shrink_start` in `hdr_seg`

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/opte#351]
We are hitting a panic in testing at the following location.

https://github.com/oxidecomputer/opte/blob/fa5c759d0e4575cb6cff227831193dd2df657d5f/opte/src/engine/packet.rs#L1308

```
panic[cpu35]/thread=fffffd3a3dcf4020: panicked at 'called `Result::unwrap()` on an `Err` value: StartPastEnd', /work/oxidecomputer/opte/opte/src/engine/packet.rs:1308:17
fffff8674aa24cf0 xde:rust_begin_unwind+146 ()
fffff8674aa24d30 xde:_ZN4core9panicking9panic_fmt17hbd42276bcaa2dfd8E+2d ()
fffff8674aa24db0 xde:_ZN4core6result13unwrap_failed17h5b67be868f6dc91bE+6c ()
fffff8674aa24f00 xde:_ZN4opte6engine6packet42Packet$LT$opte..engine..packet..Parsed$GT$16emit_new_headers17h6228ac001b3d4500E+125c ()
fffff8674aa25310 xde:_ZN4opte6engine4port13Port$LT$N$GT$7process17h9bca109443cf9deaE+2544 ()
fffff8674aa25c40 xde:xde_mc_tx+32f ()
fffff8674aa25c70 mac:mac_ring_tx+43 ()
fffff8674aa25cc0 mac:mac_provider_tx+85 ()
fffff8674aa25d80 mac:mac_tx+295 ()
fffff8674aa25e10 dld:proto_unitdata_req+273 ()
fffff8674aa25e60 dld:dld_wput+a9 ()
fffff8674aa25ed0 unix:putnext+233 ()
fffff8674aa25fe0 ip:ip_xmit+632 ()
fffff8674aa26070 ip:nce_resolv_ok+fa ()
fffff8674aa260f0 ip:ip_nce_resolve_all+ef ()
...
```

CC: @leftwo @luqmana @bnaecker

**Comment by rcgoodfellow** [comment]
Possibly the same as #349

**Comment by leftwo** [comment]
Cores for this are on catacomb at: /data/staff/core/rack2/BRM42220070/xde-kernel-panic
(cores 2 and 3 are with the latest xde driver)

**Comment by rcgoodfellow** [comment]
Looking into this dump a bit.

### Preliminaries

```
> ::status
debugging crash dump vmcore.4 (64-bit) from BRM42220070
operating system: 5.11 stlouis-0-gd760697312 (oxide)
build version: heads/stlouis-0-gd760697312

image uuid: 04e823ef-3890-6eba-aef7-e4940dec5f9c
panic message: panicked at 'called `Result::unwrap()` on an `Err` value: StartPastEnd', /work/oxidecomputer/opte/opte/src/engine/packet.rs:1308:17
dump content: kernel pages and pages from PID -1
```
```
> $C
fffff867404c5c80 vpanic()
fffff867404c5d10 rust_begin_unwind+0x146()
fffff867404c5d50 _ZN4core9panicking9panic_fmt17hbd42276bcaa2dfd8E+0x2d()
fffff867404c5dd0 _ZN4core6result13unwrap_failed17h5b67be868f6dc91bE+0x6c()
fffff867404c5f20 _ZN4opte6engine6packet42Packet$LT$opte..engine..packet..Parsed$GT$16emit_new_headers17h6228ac001b3d4500E+0x125c()
fffff867404c6330 _ZN4opte6engine4port13Port$LT$N$GT$7process17h9bca109443cf9deaE+0x2544()
fffff867404c6c60 xde_mc_tx+0x32f()
fffff867404c6c90 mac_ring_tx+0x43(fffffd3a7c2f1000, 0, fffffd3a62c04460)
fffff867404c6ce0 mac_provider_tx+0x85(fffffd3a7c2f1000, 0, fffffd3a62c04460, fffffd3a7684e4e0)
fffff867404c6da0 mac_tx+0x295(fffffd3a7684e4e0, fffffd3a62c04460, 0, 0, 0)
fffff867404c6e30 proto_unitdata_req+0x273(fffffd3ab053a018, fffffd3a37209f20)
fffff867404c6e80 dld_wput+0xa9(fffffd3a426ce158, fffffd3a37209f20)
fffff867404c6ef0 putnext+0x233(fffffd3a442408e8, fffffd3a37209f20)
fffff867404c7000 ip_xmit+0x632(fffffd3a44373180, fffffd3abd9671b8, 80400000, 4a, 0, ffffffff, fffff86700000000, 0)
fffff867404c7090 nce_resolv_ok+0xfa(fffffd3aac994bc0)
fffff867404c7110 ip_nce_resolve_all+0xef(fffffd39bae98da8, fffffd3ab74ff586, 6, fffff867404c717c, fffff867404c7188, 2)
fffff867404c7370 arp_process_packet+0x5d1(fffffd39bae98da8, fffffd3a40b3d680)
fffff867404c73c0 arp_rput+0x18b(fffffd3ab76a07b8, fffffd3a40b3d680)
fffff867404c7430 putnext+0x233(fffffd3a32a4e818, fffffd3a40b3d680)
fffff867404c74a0 dld_str_rx_unitdata+0x4f(fffffd3ab45ffe60, 0, fffffd3a69fe0a80, fffff867404c74f0)
fffff867404c7580 i_dls_link_rx+0x311(fffffd3a76b7a728, 0, fffffd3a69fe0a80, 0)
fffff867404c75d0 mac_rx_deliver+0x2e(fffffd3a7684e4e0, 0, fffffd3a69fe0a80, 0)
fffff867404c7660 mac_rx_soft_ring_process+0x1be(fffffd3a7684e4e0, fffffd3a843fc500, fffffd3a69fe0a80, fffffd3a69fe0a80, 1, 0)
fffff867404c7780 mac_rx_srs_proto_fanout+0x29a(fffffd3a84404e00, fffffd3a69fe0a80)
fffff867404c7800 mac_rx_srs_drain+0x2e5(fffffd3a84404e00, 800)
fffff867404c7890 mac_rx_srs_process+0x123(fffffd3a7c2f1000, fffffd3a84404e00, fffffd3a69fe0a80, 0)
fffff867404c78f0 mac_rx_common+0x154(fffffd3a7c2f1000, 0, fffffd3a69fe0a80)
fffff867404c7950 mac_rx+0xc6(fffffd3a7c2f1000, 0, fffffd3a69fe0a80)
fffff867404c8280 xde_mc_tx+0x499()
fffff867404c82b0 mac_ring_tx+0x43(fffffd3a7c2f1000, 0, fffffd39c5f00b60)
fffff867404c8300 mac_provider_tx+0x85(fffffd3a7c2f1000, 0, fffffd39c5f00b60, fffffd3a7684e4e0)
fffff867404c83c0 mac_tx+0x295(fffffd3a7684e4e0, fffffd39c5f00b60, 0, 0, 0)
fffff867404c8450 proto_unitdata_req+0x273(fffffd3ab45ffe60, fffffd3a69fe0a80)
fffff867404c84a0 dld_wput+0xa9(fffffd3a32a4e910, fffffd3a69fe0a80)
fffff867404c8510 putnext+0x233(fffffd3ab76a08b0, fffffd3a69fe0a80)
fffff867404c8600 arp_output+0x1fd(fffffd39bae98da8, 1, fffffd3a44091544, fffff867404c862c, fffffd3a44f3d704, fffff867404c8634, fffffd3a44f3d704)
fffff867404c8690 arp_request+0x123(fffffd3aac994bc0, 501a8c0, fffffd39bae98da8)
fffff867404c86f0 ip_ndp_resolve+0x84(fffffd3aac994bc0)
fffff867404c8800 ip_xmit+0xab5(fffffd3a44373180, fffffd3abd967268, 80006080, 4a, a756b1de, 0, fffff86700000000, fffffd3ac01ec4b0)
fffff867404c8a50 ire_send_wire_v4+0x345(fffffd3ac080b310, fffffd3a44373180, fffffd3a44740790, fffffd3ac01ec340, fffffd39bec59ef0)
fffff867404c8ad0 conn_ip_output+0x1d4(fffffd3a44373180, fffffd3ac01ec340)
fffff867404c8bb0 udp_output_connected+0x148(fffffd3ab58ef0c0, fffffd3a44373180, fffffd38cb8693a0, 1e3)
fffff867404c8c50 udp_send+0x3f2(fffffd3ab58ef0c0, fffffd3a44373180, fffff867404c8df0, fffffd38cb8693a0)
fffff867404c8ce0 so_sendmsg+0x24a(fffffd3a4407aa70, fffff867404c8df0, fffff867404c8e20, fffffd38cb8693a0)
fffff867404c8d40 socket_sendmsg+0x62(fffffd3a4407aa70, fffff867404c8df0, fffff867404c8e20, fffffd38cb8693a0)
fffff867404c8de0 sendit+0x1ab(5, fffff867404c8df0, fffff867404c8e20, 8)
fffff867404c8e90 send+0x7e(5, fe43c5bc, 2e, 0)
fffff867404c8ec0 send32+0x12(5, fe43c5bc, 2e, 0)
fffff867404c8f10 sys_syscall32+0x105()
```

### Looking at the message block that's delivered to opte via `mac_ring_tx`

```
> fffffd3a62c04460 ::print mblk_t
{
    b_next = 0
    b_prev = 0
    b_cont = 0xfffffd3a44373180
    b_rptr = 0xfffffd3a366beef0
    b_wptr = 0xfffffd3a366beefe
    b_datap = 0xfffffd3a366bee80
    b_band = 0
    b_tag = 0
    b_flag = 0
    b_queue = 0
}
```

Notably, this block only goes from `0xfffffd3a366beef0` to `0xfffffd3a366beefe`, which is 14 bytes, exactly enough room for the ethernet header only. This would seem to violate the expectation of the code linked above.

Looking at this message block we see.

```
> fffffd3a366beef0 ::dump
                   \/ 1 2 3  4 5 6 7  8 9 a b  c d e f  v123456789abcdef
fffffd3a366beef0:  a8402500 0001a840 25fffff1 08000a08  .@%....@%.......
```

Which looks like the ethernet header we expect. But then the IP header is in the continuation block.

```
> fffffd3a44373180 ::print mblk_t
{
    b_next = 0
    b_prev = 0
    b_cont = 0
    b_rptr = 0xfffffd3a44740790
    b_wptr = 0xfffffd3a447407da
    b_datap = 0xfffffd3a44740700
    b_band = 0
    b_tag = 0
    b_flag = 0
    b_queue = 0
}
```
```
> fffffd3a44740790 ::iphdr
IPv4 header
SRC                                DST
HLEN TOS  LEN   ID    OFFSET TTL   PROTO CHKSUM EXP-CSUM FLGS
192.168.1.5                        1.1.1.1
20   0    74    3     0      255   17    61687  61687    <>
```

**Comment by leftwo** [comment]
FYI, core 4 was the one where the panic inducing command was `curl -L buildomat.eng.oxide.computer`
