### ISSUE TITLE
Unwrap crash in `engine::Port<N>::process`

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/opte#357]
This was observed on a dogfood system while uploading an image through the nexus opte device. We are taking a core dump now.

https://github.com/oxidecomputer/opte/blob/1698c8b807670d5145f1b1ff5c50268470e0e50c/opte/src/engine/port.rs#L1634

```
BRM42220086 console login: WARNING: panicked at 'called `Result::unwrap()` on an `Err` value: MaxCapacity(8096)', /work/oxidecomputer/opte/opte/src/engine/port.rs:1634:21
panic[cpu78]/thread=fffff7881530dc20: panicked at 'called `Result::unwrap()` on an `Err` value: MaxCapacity(8096)', /work/oxidecomputer/opte/opte/src/engine/port.rs:1634:21

fffff7881530cb50 xde:rust_begin_unwind+146 ()
fffff7881530cb90 xde:core::panicking::panic_fmt::hbd42276bcaa2dfd8+2d ()
fffff7881530cc10 xde:core::result::unwrap_failed::h5b67be868f6dc91b+6c ()
fffff7881530d030 xde:opte::engine::port::Port<N>::process::h80b703756b89c2c8+2cba ()
fffff7881530d930 xde:xde_rx+42e ()
fffff7881530d980 mac:mac_promisc_dispatch_one+60 ()
fffff7881530da00 mac:mac_promisc_dispatch+83 ()
fffff7881530da60 mac:mac_rx_common+47 ()
fffff7881530dac0 mac:mac_rx+c6 ()
fffff7881530db00 mac:mac_rx_ring+2b ()
fffff7881530db40 t4nex:t4_intr_rx_work+b4 ()
fffff7881530db80 t4nex:t4_intr+5d ()
fffff7881530dbd0 apix:apix_dispatch_by_vector+8c ()
fffff7881530dc00 apix:apix_dispatch_lowlevel+29 ()
fffff788152c5a40 unix:switch_sp_and_call+15 ()
fffff788152c5aa0 apix:apix_do_interrupt+f2 ()
fffff788152c5ab0 unix:_interrupt+c3 ()
fffff788152c5ba0 unix:i86_mwait+12 ()
fffff788152c5bd0 unix:cpu_idle_mwait+14b ()
fffff788152c5be0 unix:cpu_idle_adaptive+19 ()
fffff788152c5c00 unix:idle+a8 ()
fffff788152c5c10 unix:thread_start+b ()
```

**Comment by luqmana** [comment]
Dupe of https://github.com/oxidecomputer/opte/issues/346?

**Comment by rcgoodfellow** [comment]
Looks like it. We'll run our next test with the build artifact from #347. Thanks @luqmana, closing for now. Will reopen if needed later.
