### ISSUE TITLE
Kernel panic if ip config is empty

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/opte#359]
During a manual setup of OPTE I hit this. It looks like either an external IP or SNAT setup is required now, and my old scripts did not have that. We should probably kick back an error here instead of panicking. This is not urgent as there is an easy workaround, and we likely won't hit this case when Omicron is running the show.

https://github.com/oxidecomputer/opte/blob/2da9dca2131869a462fc22d6e738ec257cf41de0/xde/src/xde.rs#L2016-L2043

```
panic[cpu94]/thread=fffffcfa2f76a3c0: panicked at 'called `Option::unwrap()` on a `None` value', src/xde.rs:2043:17

fffff78815c7ab50 xde:rust_begin_unwind+146 ()
fffff78815c7ab90 xde:_ZN4core9panicking9panic_fmt17hbd42276bcaa2dfd8E+2d ()
fffff78815c7abe0 xde:_ZN4core9panicking5panic17h57af998a49b567d5E+44 ()
fffff78815c7b3e0 xde:new_port+8b5 ()
fffff78815c7b740 xde:create_xde+5ee ()
fffff78815c7bc80 xde:xde_ioc_opte_cmd+5ec1 ()
fffff78815c7bcc0 xde:xde_ioctl+8b ()
fffff78815c7bd00 genunix:cdev_ioctl+3f ()
fffff78815c7bd50 specfs:spec_ioctl+55 ()
fffff78815c7bde0 genunix:fop_ioctl+40 ()
fffff78815c7bf00 genunix:ioctl+144 ()
fffff78815c7bf10 unix:brand_sys_syscall+1fe ()
```

**Comment by rcgoodfellow** [comment]
@leftwo reported an incident on a live rack being run by today where this may have occurred.

```
[8]> $C
fffffffffbe8fe40 kmdb_enter+0xb()
fffffffffbe8fe70 debug_enter+0x75(fffffffffbd5fff8)
fffffffffbe8ff60 panicsys+0x56e(fffffd00f9d6e470, fffff7881fc20b38, fffffffffbe8ff70, 1)
fffff7881fc20b20 vpanic+0x15c()
fffff7881fc20b90 0xfffffffffbca6571()
fffff7881fc20c20 xde`rust_begin_unwind+0x146()
fffff7881fc20c60 xde`_ZN4core9panicking9panic_fmt17hbd42276bcaa2dfd8E+0x2d()
fffff7881fc20cb0 xde`_ZN4core9panicking5panic17h57af998a49b567d5E+0x44()
fffff7881fc21430 xde`new_port+0x682()
fffff7881fc216b0 xde`create_xde+0x4a4()
fffff7881fc21c80 xde`xde_ioc_opte_cmd+0x5e00()
fffff7881fc21cc0 xde`xde_ioctl+0x8b()
fffff7881fc21d00 cdev_ioctl+0x3f(ab00020000, de777701, fffff5ffd09f6ab0, 202003, fffffcfa2f6d0ad8, fffff7881fc21e18)
fffff7881fc21d50 specfs`spec_ioctl+0x55(fffffcfacdee1a80, de777701, fffff5ffd09f6ab0, 202003, fffffcfa2f6d0ad8, fffff7881fc21e18, 0)
fffff7881fc21de0 fop_ioctl+0x40(fffffcfacdee1a80, de777701, fffff5ffd09f6ab0, 202003, fffffcfa2f6d0ad8, fffff7881fc21e18, 0)
fffff7881fc21f00 ioctl+0x144(12, de777701, fffff5ffd09f6ab0)
fffff7881fc21f10 sys_syscall+0x17d()
```

Dump will be available shortly.

**Comment by bnaecker** [comment]
This should be one of the panic sites tracked by #234

**Comment by bnaecker** [comment]
Confirmed that the panic @leftwo report is the same:

```
ben@jeeves /net/catacomb/data/staff/core/rack2/xde $ mdb 1
mdb: warning: dump is from SunOS 5.11 stlouis-0-g87807e07dc; dcmds and macros may not match kernel implementation
Loading modules: [ genunix specfs dtrace mac cpu.generic cpc crypto mm random smbios zfs sata ip hook neti sockfs lofs scsi_vhci arp ufs logindmux nsmb ptm ]
> $G
C++ symbol demangling enabled
> $C
fffff7881fc20b90 vpanic()
fffff7881fc20c20 rust_begin_unwind+0x146()
fffff7881fc20c60 core::panicking::panic_fmt::hbd42276bcaa2dfd8+0x2d()
fffff7881fc20cb0 core::panicking::panic::h57af998a49b567d5+0x44()
fffff7881fc21430 new_port+0x682()
fffff7881fc216b0 create_xde+0x4a4()
fffff7881fc21c80 xde_ioc_opte_cmd+0x5e00()
fffff7881fc21cc0 xde_ioctl+0x8b()
fffff7881fc21d00 cdev_ioctl+0x3f(ab00020000, de777701, fffff5ffd09f6ab0, 202003, fffffcfa2f6d0ad8, fffff7881fc21e18)
fffff7881fc21d50 spec_ioctl+0x55(fffffcfacdee1a80, de777701, fffff5ffd09f6ab0, 202003, fffffcfa2f6d0ad8, fffff7881fc21e18, 0)
fffff7881fc21de0 fop_ioctl+0x40(fffffcfacdee1a80, de777701, fffff5ffd09f6ab0, 202003, fffffcfa2f6d0ad8, fffff7881fc21e18, 0)
fffff7881fc21f00 ioctl+0x144(12, de777701, fffff5ffd09f6ab0)
fffff7881fc21f10 sys_syscall+0x17d()
> ::status
debugging crash dump vmcore.1 (64-bit) from BRM44220004
operating system: 5.11 stlouis-0-g87807e07dc (oxide)
build version: heads/stlouis-0-g87807e07dc

image uuid: efec4b5b-e8bc-4d35-fcca-8e5dbff40d12
panic message: panicked at 'called `Option::unwrap()` on a `None` value', src/xde.rs:1953:17
dump content: kernel pages and pages from PID -1
>
```

Line numbers have changed, but we're panicking at `NonZeroU32::new()` returning `None`.
