### ISSUE TITLE
Serdes failure in `opteadm` ioctl communication with driver

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/opte#72]
I'm working to get OPTE actually stood up on a physical machine for integration into the Omicron control plane. The integration code currently doesn't know how to clean up any of the OPTE/XDE devices that it creates when things go sideways. I'm using `pfexec opteadm xde-delete` to clean things up manually. Trying delete something that never existed gives a useful and correct error message:

```
bnaecker@feldspar : ~/testbed/opte-ddm-x2/cargo-bay $ pfexec ./opteadm xde-delete xde1
thread 'main' panicked at 'get link id: NotFound("link xde1 not found")', src/lib.rs:145:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

But trying to delete a device that once existed, but no longer appears to, gives a serialization error:

```
bnaecker@feldspar : ~/testbed/opte-ddm-x2/cargo-bay $ pfexec ./opteadm xde-delete xde0
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoctlFailed(DLDXdeDelete, "opte driver failed to deser/ser req/resp")', src/main.rs:626:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This error comes [from here](https://github.com/oxidecomputer/opte/blob/92659faf2b5b2ee7f6b17bd2ec773a4d085c1930/opteadm/src/lib.rs#L398), AFAICT. I don't have a lot of other context, unfortunately, but it does seem like this should result in the same `NotFound` error as the other case. It could be the device is in a partly configured state, but doesn't show up with `dladm` or `ipadm`. Those might not be the right tools, either, but I don't see any evidence of the XDE device on the system any more.

**Comment by bnaecker** [comment]
I'm going to close this. Things have moved significantly since then, and no one has seen it since. We can re-open if it becomes relevant.
